version: '3.8'

services:
  laravel-blog-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - "80:80"
    depends_on:
      - laravel-blog-php
    volumes:
      # プロジェクトに合わせる必要あり
      - ./contents:/var/www/html
    environment:
      - CONTAINER_ENV=env
      - DB_PASSWORD=root
      # プロジェクトに合わせる必要あり
      - APP_URL=http://localhost/blog
    networks:
      - laravel-blog
  laravel-blog-php:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - laravel-blog-mysql
    environment:
      - CONTAINER_ENV=dev
    # プロジェクトに合わせる必要あり
    volumes:
      - ./contents:/var/www/html
      - laravel-blog-vendor:/var/www/html/blog/vendor
    networks:
      - laravel-blog
  laravel-blog-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=general
      - MYSQL_PASSWORD=general
      - TZ=Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - laravel-blog-mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel-blog
  laravel-blog-redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel-blog

# プロジェクトに合わせる必要あり
volumes:
  laravel-blog-vendor:
  laravel-blog-mysql-data:

networks:
  laravel-blog: