FROM nginx:1.28.0

#set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/conf.d/dev.default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/fastcgi_params /etc/nginx/fastcgi_params
COPY ./docker/nginx/mime.types /etc/nginx/mime.types
# プロジェクトに合わせる必要あり
COPY --chown=www-data:www-data ./project/contents/ /var/www/html/
